import { IDriftFE, IWdisp } from '../interfaces';

export function convertDrift(wdisp?: IWdisp): IDriftFE {
  const drift: IDriftFE = {
    driftSeismicX: {
      storeyID: wdisp?.driftSeismicX.storeyID || [1],
      towerID: wdisp?.driftSeismicX.towerID || [1],
      displacement: wdisp?.driftSeismicX.displacement || [0],
      drift: wdisp?.driftSeismicX.drift || [0],
    },
    driftSeismicTwoWayX: {
      storeyID: wdisp?.driftSeismicTwoWayX.storeyID || [1],
      towerID: wdisp?.driftSeismicTwoWayX.towerID || [1],
      displacement: wdisp?.driftSeismicTwoWayX.displacement || [0],
      drift: wdisp?.driftSeismicTwoWayX.drift || [0],
    },
    driftSeismicXEccP: {
      storeyID: wdisp?.driftSeismicXEccP.storeyID || [1],
      towerID: wdisp?.driftSeismicXEccP.towerID || [1],
      displacement: wdisp?.driftSeismicXEccP.displacement || [0],
      drift: wdisp?.driftSeismicXEccP.drift || [0],
    },
    driftSeismicXEccN: {
      storeyID: wdisp?.driftSeismicXEccN.storeyID || [1],
      towerID: wdisp?.driftSeismicXEccN.towerID || [1],
      displacement: wdisp?.driftSeismicXEccN.displacement || [0],
      drift: wdisp?.driftSeismicXEccN.drift || [0],
    },
    driftSeismicY: {
      storeyID: wdisp?.driftSeismicY.storeyID || [1],
      towerID: wdisp?.driftSeismicY.towerID || [1],
      displacement: wdisp?.driftSeismicY.displacement || [0],
      drift: wdisp?.driftSeismicY.drift || [0],
    },
    driftSeismicTwoWayY: {
      storeyID: wdisp?.driftSeismicTwoWayY.storeyID || [1],
      towerID: wdisp?.driftSeismicTwoWayY.towerID || [1],
      displacement: wdisp?.driftSeismicTwoWayY.displacement || [0],
      drift: wdisp?.driftSeismicTwoWayY.drift || [0],
    },
    driftSeismicYEccP: {
      storeyID: wdisp?.driftSeismicYEccP.storeyID || [1],
      towerID: wdisp?.driftSeismicYEccP.towerID || [1],
      displacement: wdisp?.driftSeismicYEccP.displacement || [0],
      drift: wdisp?.driftSeismicYEccP.drift || [0],
    },
    driftSeismicYEccN: {
      storeyID: wdisp?.driftSeismicYEccN.storeyID || [1],
      towerID: wdisp?.driftSeismicYEccN.towerID || [1],
      displacement: wdisp?.driftSeismicYEccN.displacement || [0],
      drift: wdisp?.driftSeismicYEccN.drift || [0],
    },
    driftWindXP: {
      storeyID: wdisp?.driftWindXP.storeyID || [1],
      towerID: wdisp?.driftWindXP.towerID || [1],
      displacement: wdisp?.driftWindXP.displacement || [0],
      drift: wdisp?.driftWindXP.drift || [0],
      ratio: wdisp?.driftWindXP.ratio || [0],
      ratioD: wdisp?.driftWindXP.ratioD || [0],
    },
    driftCrossWindXP: {
      storeyID: wdisp?.driftCrossWindXP.storeyID || [1],
      towerID: wdisp?.driftCrossWindXP.towerID || [1],
      displacement: wdisp?.driftCrossWindXP.displacement || [0],
      drift: wdisp?.driftCrossWindXP.drift || [0],
      ratio: wdisp?.driftCrossWindXP.ratio || [0],
      ratioD: wdisp?.driftCrossWindXP.ratioD || [0],
    },
    driftWindXN: {
      storeyID: wdisp?.driftWindXN.storeyID || [1],
      towerID: wdisp?.driftWindXN.towerID || [1],
      displacement: wdisp?.driftWindXN.displacement || [0],
      drift: wdisp?.driftWindXN.drift || [0],
      ratio: wdisp?.driftWindXN.ratio || [0],
      ratioD: wdisp?.driftWindXN.ratioD || [0],
    },
    driftCrossWindXN: {
      storeyID: wdisp?.driftCrossWindXN.storeyID || [1],
      towerID: wdisp?.driftCrossWindXN.towerID || [1],
      displacement: wdisp?.driftCrossWindXN.displacement || [0],
      drift: wdisp?.driftCrossWindXN.drift || [0],
      ratio: wdisp?.driftCrossWindXN.ratio || [0],
      ratioD: wdisp?.driftCrossWindXN.ratioD || [0],
    },
    driftWindYP: {
      storeyID: wdisp?.driftWindYP.storeyID || [1],
      towerID: wdisp?.driftWindYP.towerID || [1],
      displacement: wdisp?.driftWindYP.displacement || [0],
      drift: wdisp?.driftWindYP.drift || [0],
      ratio: wdisp?.driftWindYP.ratio || [0],
      ratioD: wdisp?.driftWindYP.ratioD || [0],
    },
    driftCrossWindYP: {
      storeyID: wdisp?.driftCrossWindYP.storeyID || [1],
      towerID: wdisp?.driftCrossWindYP.towerID || [1],
      displacement: wdisp?.driftCrossWindYP.displacement || [0],
      drift: wdisp?.driftCrossWindYP.drift || [0],
      ratio: wdisp?.driftCrossWindYP.ratio || [0],
      ratioD: wdisp?.driftCrossWindYP.ratioD || [0],
    },
    driftWindYN: {
      storeyID: wdisp?.driftWindYN.storeyID || [1],
      towerID: wdisp?.driftWindYN.towerID || [1],
      displacement: wdisp?.driftWindYN.displacement || [0],
      drift: wdisp?.driftWindYN.drift || [0],
      ratio: wdisp?.driftWindYN.ratio || [0],
      ratioD: wdisp?.driftWindYN.ratioD || [0],
    },
    driftCrossWindYN: {
      storeyID: wdisp?.driftCrossWindYN.storeyID || [1],
      towerID: wdisp?.driftCrossWindYN.towerID || [1],
      displacement: wdisp?.driftCrossWindYN.displacement || [0],
      drift: wdisp?.driftCrossWindYN.drift || [0],
      ratio: wdisp?.driftCrossWindYN.ratio || [0],
      ratioD: wdisp?.driftCrossWindYN.ratioD || [0],
    },
    ratioSeismicX: {
      storeyID: wdisp?.ratioSeismicX.storeyID || [1],
      towerID: wdisp?.ratioSeismicX.towerID || [1],
      ratio: wdisp?.ratioSeismicX.ratio || [0],
      ratioD: wdisp?.ratioSeismicX.ratioD || [0],
    },
    ratioSeismicXEccP: {
      storeyID: wdisp?.ratioSeismicXEccP.storeyID || [1],
      towerID: wdisp?.ratioSeismicXEccP.towerID || [1],
      ratio: wdisp?.ratioSeismicXEccP.ratio || [0],
      ratioD: wdisp?.ratioSeismicXEccP.ratioD || [0],
    },
    ratioSeismicXEccN: {
      storeyID: wdisp?.ratioSeismicXEccN.storeyID || [1],
      towerID: wdisp?.ratioSeismicXEccN.towerID || [1],
      ratio: wdisp?.ratioSeismicXEccN.ratio || [0],
      ratioD: wdisp?.ratioSeismicXEccN.ratioD || [0],
    },
    ratioSeismicY: {
      storeyID: wdisp?.ratioSeismicY.storeyID || [1],
      towerID: wdisp?.ratioSeismicY.towerID || [1],
      ratio: wdisp?.ratioSeismicY.ratio || [0],
      ratioD: wdisp?.ratioSeismicY.ratioD || [0],
    },
    ratioSeismicYEccP: {
      storeyID: wdisp?.ratioSeismicYEccP.storeyID || [1],
      towerID: wdisp?.ratioSeismicYEccP.towerID || [1],
      ratio: wdisp?.ratioSeismicYEccP.ratio || [0],
      ratioD: wdisp?.ratioSeismicYEccP.ratioD || [0],
    },
    ratioSeismicYEccN: {
      storeyID: wdisp?.ratioSeismicYEccN.storeyID || [1],
      towerID: wdisp?.ratioSeismicYEccN.towerID || [1],
      ratio: wdisp?.ratioSeismicYEccN.ratio || [0],
      ratioD: wdisp?.ratioSeismicYEccN.ratioD || [0],
    },
  };

  return drift;
}
