import { IStructure, IDriftFE } from '../interfaces';

export function convertDrift(structure: IStructure): IDriftFE {
  const drift: IDriftFE = {
    driftSeismicX: {
      storeyID: structure.wdisp?.driftSeismicX.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicX.towerID || [0],
      displacement: structure.wdisp?.driftSeismicX.displacement || [0],
      drift: structure.wdisp?.driftSeismicX.drift || [0],
    },
    driftSeismicTwoWayX: {
      storeyID: structure.wdisp?.driftSeismicTwoWayX.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicTwoWayX.towerID || [0],
      displacement: structure.wdisp?.driftSeismicTwoWayX.displacement || [0],
      drift: structure.wdisp?.driftSeismicTwoWayX.drift || [0],
    },
    driftSeismicXEccP: {
      storeyID: structure.wdisp?.driftSeismicXEccP.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicXEccP.towerID || [0],
      displacement: structure.wdisp?.driftSeismicXEccP.displacement || [0],
      drift: structure.wdisp?.driftSeismicXEccP.drift || [0],
    },
    driftSeismicXEccN: {
      storeyID: structure.wdisp?.driftSeismicXEccN.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicXEccN.towerID || [0],
      displacement: structure.wdisp?.driftSeismicXEccN.displacement || [0],
      drift: structure.wdisp?.driftSeismicXEccN.drift || [0],
    },
    driftSeismicY: {
      storeyID: structure.wdisp?.driftSeismicY.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicY.towerID || [0],
      displacement: structure.wdisp?.driftSeismicY.displacement || [0],
      drift: structure.wdisp?.driftSeismicY.drift || [0],
    },
    driftSeismicTwoWayY: {
      storeyID: structure.wdisp?.driftSeismicTwoWayY.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicTwoWayY.towerID || [0],
      displacement: structure.wdisp?.driftSeismicTwoWayY.displacement || [0],
      drift: structure.wdisp?.driftSeismicTwoWayY.drift || [0],
    },
    driftSeismicYEccP: {
      storeyID: structure.wdisp?.driftSeismicYEccP.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicYEccP.towerID || [0],
      displacement: structure.wdisp?.driftSeismicYEccP.displacement || [0],
      drift: structure.wdisp?.driftSeismicYEccP.drift || [0],
    },
    driftSeismicYEccN: {
      storeyID: structure.wdisp?.driftSeismicYEccN.storeyID || [0],
      towerID: structure.wdisp?.driftSeismicYEccN.towerID || [0],
      displacement: structure.wdisp?.driftSeismicYEccN.displacement || [0],
      drift: structure.wdisp?.driftSeismicYEccN.drift || [0],
    },
    driftWindXP: {
      storeyID: structure.wdisp?.driftWindXP.storeyID || [0],
      towerID: structure.wdisp?.driftWindXP.towerID || [0],
      displacement: structure.wdisp?.driftWindXP.displacement || [0],
      drift: structure.wdisp?.driftWindXP.drift || [0],
      ratio: structure.wdisp?.driftWindXP.ratio || [0],
      ratioD: structure.wdisp?.driftWindXP.ratioD || [0],
    },
    driftCrossWindXP: {
      storeyID: structure.wdisp?.driftCrossWindXP.storeyID || [0],
      towerID: structure.wdisp?.driftCrossWindXP.towerID || [0],
      displacement: structure.wdisp?.driftCrossWindXP.displacement || [0],
      drift: structure.wdisp?.driftCrossWindXP.drift || [0],
      ratio: structure.wdisp?.driftCrossWindXP.ratio || [0],
      ratioD: structure.wdisp?.driftCrossWindXP.ratioD || [0],
    },
    driftWindXN: {
      storeyID: structure.wdisp?.driftWindXN.storeyID || [0],
      towerID: structure.wdisp?.driftWindXN.towerID || [0],
      displacement: structure.wdisp?.driftWindXN.displacement || [0],
      drift: structure.wdisp?.driftWindXN.drift || [0],
      ratio: structure.wdisp?.driftWindXN.ratio || [0],
      ratioD: structure.wdisp?.driftWindXN.ratioD || [0],
    },
    driftCrossWindXN: {
      storeyID: structure.wdisp?.driftCrossWindXN.storeyID || [0],
      towerID: structure.wdisp?.driftCrossWindXN.towerID || [0],
      displacement: structure.wdisp?.driftCrossWindXN.displacement || [0],
      drift: structure.wdisp?.driftCrossWindXN.drift || [0],
      ratio: structure.wdisp?.driftCrossWindXN.ratio || [0],
      ratioD: structure.wdisp?.driftCrossWindXN.ratioD || [0],
    },
    driftWindYP: {
      storeyID: structure.wdisp?.driftWindYP.storeyID || [0],
      towerID: structure.wdisp?.driftWindYP.towerID || [0],
      displacement: structure.wdisp?.driftWindYP.displacement || [0],
      drift: structure.wdisp?.driftWindYP.drift || [0],
      ratio: structure.wdisp?.driftWindYP.ratio || [0],
      ratioD: structure.wdisp?.driftWindYP.ratioD || [0],
    },
    driftCrossWindYP: {
      storeyID: structure.wdisp?.driftCrossWindYP.storeyID || [0],
      towerID: structure.wdisp?.driftCrossWindYP.towerID || [0],
      displacement: structure.wdisp?.driftCrossWindYP.displacement || [0],
      drift: structure.wdisp?.driftCrossWindYP.drift || [0],
      ratio: structure.wdisp?.driftCrossWindYP.ratio || [0],
      ratioD: structure.wdisp?.driftCrossWindYP.ratioD || [0],
    },
    driftWindYN: {
      storeyID: structure.wdisp?.driftWindYN.storeyID || [0],
      towerID: structure.wdisp?.driftWindYN.towerID || [0],
      displacement: structure.wdisp?.driftWindYN.displacement || [0],
      drift: structure.wdisp?.driftWindYN.drift || [0],
      ratio: structure.wdisp?.driftWindYN.ratio || [0],
      ratioD: structure.wdisp?.driftWindYN.ratioD || [0],
    },
    driftCrossWindYN: {
      storeyID: structure.wdisp?.driftCrossWindYN.storeyID || [0],
      towerID: structure.wdisp?.driftCrossWindYN.towerID || [0],
      displacement: structure.wdisp?.driftCrossWindYN.displacement || [0],
      drift: structure.wdisp?.driftCrossWindYN.drift || [0],
      ratio: structure.wdisp?.driftCrossWindYN.ratio || [0],
      ratioD: structure.wdisp?.driftCrossWindYN.ratioD || [0],
    },
    ratioSeismicX: {
      storeyID: structure.wdisp?.ratioSeismicX.storeyID || [0],
      towerID: structure.wdisp?.ratioSeismicX.towerID || [0],
      ratio: structure.wdisp?.ratioSeismicX.ratio || [0],
      ratioD: structure.wdisp?.ratioSeismicX.ratioD || [0],
    },
    ratioSeismicXEccP: {
      storeyID: structure.wdisp?.ratioSeismicXEccP.storeyID || [0],
      towerID: structure.wdisp?.ratioSeismicXEccP.towerID || [0],
      ratio: structure.wdisp?.ratioSeismicXEccP.ratio || [0],
      ratioD: structure.wdisp?.ratioSeismicXEccP.ratioD || [0],
    },
    ratioSeismicXEccN: {
      storeyID: structure.wdisp?.ratioSeismicXEccN.storeyID || [0],
      towerID: structure.wdisp?.ratioSeismicXEccN.towerID || [0],
      ratio: structure.wdisp?.ratioSeismicXEccN.ratio || [0],
      ratioD: structure.wdisp?.ratioSeismicXEccN.ratioD || [0],
    },
    ratioSeismicY: {
      storeyID: structure.wdisp?.ratioSeismicY.storeyID || [0],
      towerID: structure.wdisp?.ratioSeismicY.towerID || [0],
      ratio: structure.wdisp?.ratioSeismicY.ratio || [0],
      ratioD: structure.wdisp?.ratioSeismicY.ratioD || [0],
    },
    ratioSeismicYEccP: {
      storeyID: structure.wdisp?.ratioSeismicYEccP.storeyID || [0],
      towerID: structure.wdisp?.ratioSeismicYEccP.towerID || [0],
      ratio: structure.wdisp?.ratioSeismicYEccP.ratio || [0],
      ratioD: structure.wdisp?.ratioSeismicYEccP.ratioD || [0],
    },
    ratioSeismicYEccN: {
      storeyID: structure.wdisp?.ratioSeismicYEccN.storeyID || [0],
      towerID: structure.wdisp?.ratioSeismicYEccN.towerID || [0],
      ratio: structure.wdisp?.ratioSeismicYEccN.ratio || [0],
      ratioD: structure.wdisp?.ratioSeismicYEccN.ratioD || [0],
    },
  };

  return drift;
}
